### ISSUE TITLE
页面日志中不应显示自动巡查日志

### ISSUE THREAD

**Issue by AnnAngela** [FishThirteen/MoegirlOperationTool#4]
日志处过滤自动巡查日志
![hj1isoty mjbwsdfrk okml](https://cloud.githubusercontent.com/assets/9762652/7553378/5b0afb30-f727-11e4-9b5e-7b253724ffac.png)
原谅我取名难……你现在应该懂我为什么喜欢用a,b,c,d做变量名了吧……

**Comment by MoeMoeFish** [comment]
@AnnAngela  已解决
